name: Lint

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Dependenses installation
        run:
          make install
          
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          make lint
